USE IICT_CONSTRUCTION_SITE_MANAGEMENT_SYSTEM;

CREATE TABLE Employee_Salary_Table(ID INT IDENTITY(1,1),
NO_OF_DAYS_PRESENT FLOAT,
OVER_TIME FLOAT,
TOTAL_WORK  AS NO_OF_DAYS_PRESENT+OVER_TIME,
NET_PAY FLOAT,
ADVANCE_TAKEN FLOAT,
BALAENCE_OF_PAY AS NET_PAY-ADVANCE_TAKEN+OVER_TIME*(NET_PAY/30),
DATE_OF_PAYMENT DATE,
SALARY_OF_MONTH VARCHAR(30),
EMPOLYEE_ID INT FOREIGN KEY REFERENCES Employee_Table(EMPLOYEE_ID)
ON DELETE CASCADE
ON UPDATE CASCADE);
INSERT INTO Employee_Salary_Table(NO_OF_DAYS_PRESENT,OVER_TIME,NET_PAY,ADVANCE_TAKEN,DATE_OF_PAYMENT,SALARY_OF_MONTH,EMPOLYEE_ID)
VALUES(30,0,40000,2300,'2022-05-01','APRIL',10001);
INSERT INTO Employee_Salary_Table(NO_OF_DAYS_PRESENT,OVER_TIME,NET_PAY,ADVANCE_TAKEN,DATE_OF_PAYMENT,SALARY_OF_MONTH,EMPOLYEE_ID)
VALUES(30,0,30000,2500,'2022-05-01','APRIL',10017);
INSERT INTO Employee_Salary_Table(NO_OF_DAYS_PRESENT,OVER_TIME,NET_PAY,ADVANCE_TAKEN,DATE_OF_PAYMENT,SALARY_OF_MONTH,EMPOLYEE_ID)
VALUES(30,2.5,12000,2500,'2022-05-01','APRIL',10018);
INSERT INTO Employee_Salary_Table(NO_OF_DAYS_PRESENT,OVER_TIME,NET_PAY,ADVANCE_TAKEN,DATE_OF_PAYMENT,SALARY_OF_MONTH,EMPOLYEE_ID)
VALUES(28,2.5,12000,2500,'2022-05-01','APRIL',10002);



DELETE FROM Employee_Salary_Table WHERE ID=1;


SELECT *FROM Employee_Salary_Table;
SELECT *FROM Employee_Table;
SELECT *FROM Foreman_Payment_Table;
DROP TABLE Employee_Salary_Table;





