
use IICT_CONSTRUCTION_SITE_MANAGEMENT_SYSTEM;

create table Fixed_Equipment_Tbl(
EQUIPMENT_ID INT,
EQUIPMENT_TYPE VARCHAR(30),
TOTAL_EQUIPMENT_NO INT,
BROKEN_EQUIPMENT INT,
AVAILABLE_EQUIPMENT AS TOTAL_EQUIPMENT_NO-BROKEN_EQUIPMENT,
MANAGER_ID INT FOREIGN KEY REFERENCES Manager_Table(MANAGER_ID)
ON DELETE CASCADE
ON UPDATE CASCADE

);
INSERT INTO Fixed_Equipment_Tbl VALUES(101,'Kodal',10,2,30002);
INSERT INTO Fixed_Equipment_Tbl VALUES(102,'Hatur',5,0,30002);
INSERT INTO Fixed_Equipment_Tbl VALUES(103,'Balti',20,4,30002);

INSERT INTO Fixed_Equipment_Tbl VALUES(104,'Mixure',5,1,30002);
INSERT INTO Fixed_Equipment_Tbl VALUES(105,'Korai',20,0,30002);
INSERT INTO Fixed_Equipment_Tbl VALUES(106,'Keni',20,4,30002);
INSERT INTO Fixed_Equipment_Tbl VALUES(107,'Drill Machine',5,0,30002);
INSERT INTO Fixed_Equipment_Tbl VALUES(108,'Rod Cutter',7,1,30002);
INSERT INTO Fixed_Equipment_Tbl VALUES(109,'Jhalay Machine',9,0,30002);



drop TABLE Fixed_Equipment_Tbl;

SELECT *FROM Fixed_Equipment_Tbl;

update Fixed_Equipment_Tbl set BROKEN_EQUIPMENT=3 WHERE EQUIPMENT_ID=101;
