USE IICT_CONSTRUCTION_SITE_MANAGEMENT_SYSTEM;

CREATE TABLE Foreman_Table(FOREMAN_ID INT IDENTITY(20001,1) PRIMARY KEY,
[TYPE] VARCHAR(30),
EMPLOYEE_ID INT FOREIGN KEY REFERENCES Employee_Table(EMPLOYEE_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO Foreman_Table VALUES('Raj Mistri',10002)

INSERT INTO Foreman_Table VALUES('Tiels Mistri',10013)
INSERT INTO Foreman_Table VALUES('Tai Mistri',10014)

INSERT INTO Foreman_Table VALUES('Wire Link Mistri',10015)
INSERT INTO Foreman_Table VALUES('Sanetari Mistri',10016)
INSERT INTO Foreman_Table VALUES('Tiels',10021)





SELECT * FROM Foreman_Table;
DROP TABLE Foreman_Table;

