use IICT_CONSTRUCTION_SITE_MANAGEMENT_SYSTEM;

CREATE TABLE Foreman_Salary_Table(
NO_OF_DAYS_PRESENT FLOAT,
OVER_TIME FLOAT,
TOTAL_WORK  AS NO_OF_DAYS_PRESENT+OVER_TIME,
NET_PAY_PER_DAY FLOAT,
ADVANCE_TAKEN float,
BALAENCE_OF_PAY AS (NET_PAY_PER_DAY*(NO_OF_DAYS_PRESENT+OVER_TIME)) -ADVANCE_TAKEN,
DATE_OF_PAYMENT DATE,
SALARY_OF_MONTH VARCHAR(30),
EMPOLYEE_ID INT FOREIGN KEY REFERENCES Employee_Table(EMPLOYEE_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
);

INSERT INTO Foreman_Salary_Table(NO_OF_DAYS_PRESENT,OVER_TIME,NET_PAY_PER_DAY,ADVANCE_TAKEN,DATE_OF_PAYMENT,SALARY_OF_MONTH,EMPOLYEE_ID)VALUES(42,10,300,2500,'2022-05-01','APRIL',10002);
INSERT INTO Foreman_Salary_Table(NO_OF_DAYS_PRESENT,OVER_TIME,NET_PAY_PER_DAY,ADVANCE_TAKEN,DATE_OF_PAYMENT,SALARY_OF_MONTH,EMPOLYEE_ID)VALUES(33,11,400,2500,'2022-05-01','APRIL',10013);
INSERT INTO Foreman_Salary_Table(NO_OF_DAYS_PRESENT,OVER_TIME,NET_PAY_PER_DAY,ADVANCE_TAKEN,DATE_OF_PAYMENT,SALARY_OF_MONTH,EMPOLYEE_ID)VALUES(30,4,300,2000,'2022-05-01','APRIL',10014);
INSERT INTO Foreman_Salary_Table(NO_OF_DAYS_PRESENT,OVER_TIME,NET_PAY_PER_DAY,ADVANCE_TAKEN,DATE_OF_PAYMENT,SALARY_OF_MONTH,EMPOLYEE_ID)VALUES(30,0,500,1800,'2022-05-01','APRIL',10015);

INSERT INTO Foreman_Salary_Table(NO_OF_DAYS_PRESENT,OVER_TIME,NET_PAY_PER_DAY,ADVANCE_TAKEN,DATE_OF_PAYMENT,SALARY_OF_MONTH,EMPOLYEE_ID)VALUES(30,10,300,10000,'2022-05-01','APRIL',10016);

select*from Foreman_Salary_Table;
delete from Foreman_Salary_Table where EMPOLYEE_ID=10001

SELECT SUM(NUMBER_OF_LABOUR_PRESENT) FROM Foreman_Payment_Table WHERE FOREMAN_ID=20002;
SELECT *FROM Employee_Table WHERE EMPLOYEE_DESIGNATION='Foreman';
TRUNCATE TABLE Foreman_Salary_Table;
SELECT *FROM Foreman_Payment_Table;
SELECT *FROM Foreman_Salary_Table;

truncate table Foreman_Payment_Table;
DROP TABLE Foreman_Salary_Table;

